server:
  port: 8080 # Внешний порт для клиента

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            # Все запросы, начинающиеся с /api/users/, пойдут сюда
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCB
                # Если user-service упадет, запрос перекинется на этот эндпоинт внутри Gateway
                fallbackUri: forward:/fallback/user-fallback
        - id: notification-service-route
          # lb:// заставляет Gateway спросить у Eureka порт для "notification-service"
          uri: lb://notification-service
          predicates:
            # Все запросы на http://localhost:8080/api/mail/** уйдут в этот сервис
            - Path=/api/mail/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationServiceCB
                # Если сервис уведомлений упадет, вызовется этот fallback
                fallbackUri: forward:/fallback/notification-fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Адрес сервера Eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG